name: docs
type: php:7.2
disk: 1024
web:
  locations:
    "/":
      root: ""
      passthru: /index.php
      expires: 1h
mounts:
    '/cache': 'shared:files/cache'
    '/logs': 'shared:files/logs'
    '/images': 'shared:files/images'
    '/assets': 'shared:files/assets'
    '/user/data': 'shared:files/user-data'
    '/backup': 'shared:files/backup'
    '/tmp': 'shared:files/tmp'
hooks:
  deploy: |
    set -e
    bin/plugin tntsearch index
