name: docs
type: php:7.2
disk: 2048
web:
    locations:
        "/":
            root: ""
            passthru: /index.php
            expires: 1h
mounts:
    '/cache': 'shared:files/cache'
    '/logs': 'shared:files/logs'
    '/images': 'shared:files/images'
    '/assets': 'shared:files/assets'
    '/user/data': 'shared:files/user-data'
    '/backup': 'shared:files/backup'
    '/tmp': 'shared:files/tmp'
hooks:
  build: |
    curl -fsS https://platform.sh/cli/installer | php
crons:
    backup:
        # Trigger a backup at 5 am (UTC) every day.
        spec: '0 5 * * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform backup:create --yes --no-wait
            fi
    renewcert:
        # Force a redeploy at 7 am (UTC) on the 1st and 15th of every month.
        spec: '0 7 1,15 * *'
        cmd: |
            if [ "$PLATFORM_BRANCH" = master ]; then
                platform redeploy --yes --no-wait
            fi